In [2]:
import numpy as np
import pandas as pd
from IPython.display import display

In [4]:
df = pd.read_csv('mpg.csv')

display(df)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
mpg,398.0,23.514573,7.815984,9.0,17.500,23.0,29.000,46.6
cylinders,398.0,5.454774,1.701004,3.0,4.000,4.0,8.000,8.0
displacement,398.0,193.425879,104.269838,68.0,104.250,148.5,262.000,455.0
weight,398.0,2970.424623,846.841774,1613.0,2223.750,2803.5,3608.000,5140.0
acceleration,398.0,15.568090,2.757689,8.0,13.825,15.5,17.175,24.8
model_year,398.0,76.010050,3.697627,70.0,73.000,76.0,79.000,82.0
origin,398.0,1.572864,0.802055,1.0,1.000,1.0,2.000,3.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [19]:
df_mean_per_group_mpg = df.groupby('model_year').mean(numeric_only=True)
df_mean_per_group_mpg['mpg']
df_mean_per_group_mpg.loc[70:75].tail(2)

,mpg,cylinders,displacement,weight,acceleration,origin
model_year,,,,,,
74,22.703704,5.259259,171.740741,2877.925926,16.203704,1.666667
75,20.266667,5.600000,205.533333,3176.800000,16.050000,1.466667

In [22]:
df_mean_per_group_mpg = df.groupby('model_year').max(numeric_only=True)
df_mean_per_group_mpg

             mpg  cylinders  displacement  weight  acceleration  origin
model_year
70          27.0          8         455.0    4732          20.5       3
71          35.0          8         400.0    5140          20.5       3
72          28.0          8         429.0    4633          23.5       3
73          29.0          8         455.0    4997          21.0       3
74          32.0          8         350.0    4699          21.0       3
75          33.0          8         400.0    4668          21.0       3
76          33.0          8         351.0    4380          22.2       3
77          36.0          8         400.0    4335          19.0       3
78          43.1          8         318.0    4080          21.5       3
79          37.3          8         360.0    4360          24.8       3
80          46.6          6         225.0    3381          23.7       3
81          39.1          8         350.0    3725          20.7       3
82          44.0          6         262.0    3035          24.6       3

In [28]:
#df_mean_per_group_mpg = df.groupby('model_year').value_counts()
df['model_year'].value_counts().sort_index()

model_year
70    29
71    28
72    28
73    40
74    27
75    30
76    34
77    28
78    36
79    29
80    29
81    29
82    31
Name: count, dtype: int64

In [30]:
# find the 5 highest mpg mean value + year (group by year)